"use client";

import { useState } from "react";
import Markdown from "react-markdown";
import type { InstallGuideStatus } from "@/lib/types";

function StatusBadge({ status }: { status: InstallGuideStatus }) {
  switch (status) {
    case "draft":
      return (
        <span className="inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full bg-orange-100 text-orange-700 border border-orange-200">
          Draft — community verifying
        </span>
      );
    case "verified":
      return (
        <span className="inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full bg-green-100 text-green-700 border border-green-200">
          ✓ Verified working
        </span>
      );
    case "broken":
      return (
        <span className="inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full bg-red-100 text-red-700 border border-red-200">
          ⚠️ Reports of issues — see below
        </span>
      );
    default:
      return null;
  }
}

interface FeedbackProps {
  codeId: string;
  isAuthenticated: boolean;
}

function GuideFeedback({ codeId, isAuthenticated }: FeedbackProps) {
  const [submitted, setSubmitted] = useState<"helpful" | "error" | null>(null);
  const [showReport, setShowReport] = useState(false);
  const [note, setNote] = useState("");
  const [loading, setLoading] = useState(false);

  async function submit(action: "helpful" | "error", reportNote?: string) {
    if (!isAuthenticated || loading) return;
    setLoading(true);
    try {
      const res = await fetch("/api/install-guide/feedback", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code_id: codeId, action, note: reportNote }),
      });
      if (res.ok) {
        setSubmitted(action);
        setShowReport(false);
      }
    } finally {
      setLoading(false);
    }
  }

  if (!isAuthenticated) {
    return (
      <p className="text-xs text-[var(--color-ink-muted)] mt-4">
        Sign in to leave feedback on this guide.
      </p>
    );
  }

  if (submitted) {
    return (
      <p className="text-sm text-green-700 mt-4">
        {submitted === "helpful" ? "Thanks for the feedback!" : "Report submitted — we'll look into it."}
      </p>
    );
  }

  return (
    <div className="mt-4 space-y-3">
      <div className="flex items-center gap-3">
        <span className="text-sm text-[var(--color-ink-muted)]">Was this helpful?</span>
        <button
          onClick={() => submit("helpful")}
          disabled={loading}
          className="btn-ghost text-xs py-1 px-3"
        >
          👍 Yes
        </button>
        <button
          onClick={() => setShowReport(true)}
          disabled={loading}
          className="btn-ghost text-xs py-1 px-3"
        >
          👎 Report an error
        </button>
      </div>
      {showReport && (
        <div className="space-y-2">
          <textarea
            value={note}
            onChange={(e) => setNote(e.target.value)}
            placeholder="What went wrong? (optional)"
            className="w-full border rounded p-2 text-sm bg-[var(--color-cream)] border-[var(--color-ink-muted)]"
            rows={3}
          />
          <div className="flex gap-2">
            <button
              onClick={() => submit("error", note || undefined)}
              disabled={loading}
              className="btn-primary text-xs py-1 px-3"
            >
              Submit report
            </button>
            <button
              onClick={() => setShowReport(false)}
              className="btn-ghost text-xs py-1 px-3"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

interface InstallGuideProps {
  codeId: string;
  guide: string;
  status: InstallGuideStatus;
  author: string | null;
  updatedAt: string | null;
  isAuthenticated: boolean;
}

export function InstallGuide({
  codeId,
  guide,
  status,
  author,
  updatedAt,
  isAuthenticated,
}: InstallGuideProps) {
  return (
    <section className="mb-8">
      <div className="flex items-center gap-3 mb-3">
        <h2 className="font-semibold text-xl">Install Guide</h2>
        <StatusBadge status={status} />
      </div>
      {author && (
        <p className="text-xs text-[var(--color-ink-muted)] mb-4">
          Generated by {author}
          {updatedAt && <> · {new Date(updatedAt).toLocaleDateString()}</>}
        </p>
      )}
      <div className="prose-vault text-sm space-y-4 [&_pre]:bg-[var(--color-ink)] [&_pre]:text-[var(--color-cream)] [&_pre]:p-4 [&_pre]:rounded [&_pre]:text-xs [&_pre]:font-mono [&_pre]:overflow-x-auto [&_code]:bg-[var(--color-ink)]/10 [&_code]:px-1 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-xs [&_code]:font-mono [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_table]:w-full [&_table]:text-xs [&_th]:text-left [&_th]:p-2 [&_th]:border-b [&_th]:border-[var(--color-ink-muted)]/20 [&_td]:p-2 [&_td]:border-b [&_td]:border-[var(--color-ink-muted)]/10 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:mt-6 [&_h2]:mb-2 [&_h3]:font-semibold [&_h3]:mt-4 [&_h3]:mb-1 [&_ul]:list-disc [&_ul]:ml-5 [&_ol]:list-decimal [&_ol]:ml-5 [&_li]:mb-1 [&_a]:text-[var(--color-orange-dark)] [&_a]:underline">
        <Markdown>{guide}</Markdown>
      </div>
      <GuideFeedback codeId={codeId} isAuthenticated={isAuthenticated} />
    </section>
  );
}

export function InstallGuideMissing() {
  return (
    <section className="mb-8">
      <h2 className="font-semibold text-xl mb-3">Install Guide</h2>
      <div className="card bg-[var(--color-cream)] border-dashed">
        <p className="text-sm text-[var(--color-ink-muted)] mb-2">
          Install guide coming — help us verify this integration.
        </p>
        <a
          href="https://github.com/selucas12/vault/issues"
          target="_blank"
          rel="noreferrer"
          className="text-sm text-[var(--color-orange-dark)] underline"
        >
          Contribute on GitHub →
        </a>
      </div>
    </section>
  );
}
