import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of service",
  description: "Terms governing your use of Vault, a subscription directory by Cheesyboy.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <article className="max-w-3xl mx-auto px-6 py-12 prose-vault">
      <h1 className="text-3xl font-bold mb-2">Terms of service</h1>
      <p className="text-sm text-[var(--color-ink-muted)] mb-8">Last updated: May 24, 2026</p>

      <Section title="1. Definitions">
        <p><strong>Vault</strong> refers to the product and website at vault.cheesyboy.dev, operated by Cheesyboy (Bubbles LLC, San Juan, PR).</p>
        <p><strong>Subscriber</strong> means anyone with an active paid subscription.</p>
        <p><strong>Content</strong> means the integration listings, descriptions, AI search results, and curated metadata in the directory.</p>
      </Section>

      <Section title="2. Account requirements">
        <p>You must be at least 18 years old to subscribe. You agree to provide accurate information when creating your account. One account per person — don&apos;t share credentials.</p>
      </Section>

      <Section title="3. Subscription terms">
        <p>Vault offers two plans: Monthly ($9.99/month) and Annual ($99/year). Both auto-renew unless you cancel. You can cancel anytime from your <a href="/account" className="text-[var(--color-orange-dark)] underline">account page</a>.</p>
        <p>Cancellation stops future renewals but doesn&apos;t refund the current billing period. For refunds, see our <a href="/refund" className="text-[var(--color-orange-dark)] underline">refund policy</a>.</p>
      </Section>

      <Section title="4. Acceptable use">
        <p>You may use Vault to discover and install integrations for your own projects. You may not:</p>
        <ul className="list-disc ml-6 space-y-1 text-[var(--color-ink-muted)]">
          <li>Systematically scrape, mirror, or redistribute the directory contents</li>
          <li>Resell access to your subscription or share your account</li>
          <li>Reverse-engineer the AI search pipeline or our embeddings</li>
          <li>Use the service to build a competing directory</li>
        </ul>
      </Section>

      <Section title="5. Intellectual property">
        <p>Vault&apos;s design, branding, and curation are &copy; Cheesyboy (Bubbles LLC). The integrations listed belong to their respective authors — we link to them and credit them but don&apos;t claim ownership.</p>
      </Section>

      <Section title="6. Disclaimers">
        <p>The directory is provided &ldquo;as is.&rdquo; We do our best to verify listed integrations, but we can&apos;t guarantee every entry works perfectly. Third-party integrations are maintained by their authors, not by us.</p>
        <p>AI search results are generated by language models and may occasionally be inaccurate. Use your judgment when installing any software.</p>
      </Section>

      <Section title="7. Limitation of liability">
        <p>Our total liability to you is capped at the amount you&apos;ve paid us in the last 12 months. We&apos;re not liable for indirect, incidental, or consequential damages.</p>
      </Section>

      <Section title="8. Termination">
        <p>We may terminate your account if you violate these terms. We&apos;ll email you first unless the violation is severe (e.g., abuse, scraping at scale). You can delete your account anytime by emailing us.</p>
      </Section>

      <Section title="9. Governing law">
        <p>These terms are governed by the laws of Puerto Rico, USA. Any disputes will be resolved in the courts of San Juan, PR.</p>
      </Section>

      <Section title="10. Changes">
        <p>We may update these terms from time to time. For material changes, we&apos;ll email active subscribers at least 14 days before the change takes effect. Continued use after the effective date constitutes acceptance.</p>
      </Section>

      <p className="mt-8 text-sm text-[var(--color-ink-muted)]">
        Questions about these terms? Email{" "}
        <a href="mailto:meow@cheesyboy.dev" className="underline">meow@cheesyboy.dev</a>.
      </p>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-semibold mb-3">{title}</h2>
      <div className="space-y-2 text-[var(--color-ink)]">{children}</div>
    </section>
  );
}
